//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace NewAge.Logger.Data.Entities
{
    public partial class NewAgeLoggerContainer : ObjectContext
    {
        public const string ConnectionString = "name=NewAgeLoggerContainer";
        public const string ContainerName = "NewAgeLoggerContainer";
    
        #region Constructors
    
        public NewAgeLoggerContainer()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        public NewAgeLoggerContainer(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        public NewAgeLoggerContainer(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<LogError> LogErrors
        {
            get { return _logErrors  ?? (_logErrors = CreateObjectSet<LogError>("LogErrors")); }
        }
        private ObjectSet<LogError> _logErrors;
    
        public ObjectSet<LogPerformance> LogPerformances
        {
            get { return _logPerformances  ?? (_logPerformances = CreateObjectSet<LogPerformance>("LogPerformances")); }
        }
        private ObjectSet<LogPerformance> _logPerformances;

        #endregion
    }
}
